apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: inference-server:latest  # The image I built
          imagePullPolicy: Never          # Important for local images
          ports:
            - containerPort: 8000